"""remove: Ledger location과 event_name 필드 제거

Revision ID: 37facef01e30
Revises: 20250920_fix_created_at
Create Date: 2025-09-20 20:52:08.219900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37facef01e30'
down_revision: Union[str, Sequence[str], None] = '20250920_fix_created_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledgers', 'location')
    op.drop_column('ledgers', 'event_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledgers', sa.Column('event_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='경조사 이름 (예: 김철수 결혼식)'))
    op.add_column('ledgers', sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='경조사 장소'))
    # ### end Alembic commands ###
