"""empty message

Revision ID: 7ff6b21c9f02
Revises: 10e1ae68874e
Create Date: 2025-09-19 22:26:49.407582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff6b21c9f02'
down_revision: Union[str, Sequence[str], None] = '10e1ae68874e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='전체 알림 켜기/끄기'),
    sa.Column('event_reminders', sa.Boolean(), nullable=False, comment='일정 알림'),
    sa.Column('reminder_hours_before', sa.Integer(), nullable=False, comment='몇 시간 전에 알림'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.add_column('schedules', sa.Column('status', sa.String(length=20), nullable=True, comment='일정 상태'))
    op.drop_column('schedules', 'description')
    op.drop_column('users', 'push_notification_enabled')
    op.drop_column('users', 'notification_advance_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_advance_hours', sa.INTEGER(), autoincrement=False, nullable=True, comment='알림 시간 (시간 단위, 기본값: 2시간 전)'))
    op.add_column('users', sa.Column('push_notification_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='푸시 알림 활성화'))
    op.add_column('schedules', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='일정 설명'))
    op.drop_column('schedules', 'status')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
