"""Add event_date and event_time columns

Revision ID: c1c18bc9e200
Revises: 
Create Date: 2025-09-06 17:22:03.340105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c18bc9e200'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 기존 컬럼 삭제 (타입 변환 오류 방지)
    op.drop_column('ledgers', 'created_at')
    op.drop_column('ledgers', 'updated_at')
    op.drop_column('schedules', 'start_time')

    # 2. 새 컬럼 추가
    op.add_column('ledgers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ledgers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # 3. 기본값 설정
    op.execute("UPDATE ledgers SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE ledgers SET updated_at = NOW() WHERE updated_at IS NULL")

    # 4. NOT NULL 제약조건 추가
    op.alter_column('ledgers', 'created_at', nullable=False)
    op.alter_column('ledgers', 'updated_at', nullable=False)

    # 5. schedules 테이블에 새 컬럼 추가
    op.add_column('schedules', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('schedules', sa.Column('event_time', sa.Time(), nullable=True))

    # 6. 기존 데이터 변환
    op.execute("""
        UPDATE schedules 
        SET event_date = start_time::date, 
            event_time = start_time::time
        WHERE start_time IS NOT NULL
    """)

    # 7. NOT NULL 제약조건 추가
    op.alter_column('schedules', 'event_date', nullable=False)
    op.alter_column('schedules', 'event_time', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 롤백 로직
    op.drop_column('schedules', 'event_time')
    op.drop_column('schedules', 'event_date')

    op.drop_column('ledgers', 'created_at')
    op.drop_column('ledgers', 'updated_at')

    # 기존 컬럼 복원
    op.add_column('ledgers', sa.Column('created_at', sa.String(50), nullable=True))
    op.add_column('ledgers', sa.Column('updated_at', sa.String(50), nullable=True))
    # ### end Alembic commands ###
