"""알림 테이블 날짜 시간 분리 및 유저테이블 FCM토큰 필드 추가

Revision ID: dd0d11d4486b
Revises: 37facef01e30
Create Date: 2025-09-25 23:24:12.195669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd0d11d4486b'
down_revision: Union[str, Sequence[str], None] = '37facef01e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('event_type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('notifications', sa.Column('event_time', sa.Time(), nullable=True))
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'date')
    op.add_column('users', sa.Column('fcm_token', sa.String(length=255), nullable=True, comment='Firebase FCM 토큰'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.add_column('notifications', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'event_time')
    op.drop_column('notifications', 'event_date')
    op.drop_column('notifications', 'event_type')
    # ### end Alembic commands ###
